### PR TITLE
Throw stuff upstream

### PR DESCRIPTION
**Pull request by dscho**
This Pull Request is not meant to be merged as-is, but rather serves as a public record what has been pushed upstream already, what needs to be dropped, and what has to be developed further before being submitted upstream.

It is also discussed in this mail thread: http://micro-manager.3463995.n2.nabble.com/Various-OpenSPIM-stuff-td7584359.html

Under discussion:
- [ ] Favor Ivy downloads over 3rdpartypublic even more: _Merge 'macosx-build' into HEAD_

Needs work:
- [ ] Allow Micro-Manager to be loaded by a class loader different from the system class loader: _Never use the system class loader_
- [ ] Integrate mmstudio into the Visual Studio build: _Add a Visual Studio project for mmstudio_
- [ ] Port everything to use commons-math3 (incomplete!!!): _Merge 'commons-math3' into HEAD_

Accepted:
- [x] Some fixes for The Imaging Source camera: _TIScam: Fixes to device adapter_
- [x] A bug fix (probably still relevant): _MMCore cannot return a zStageLabel that is null, only an empty one._

To drop (was reimplemented differently by the Micro-Manager team in the meantime):
- [x] Provide a convenience method to log exceptions: _ReportingUtils: add a convenient logException() method_
- [x] Possibly obsolete support to allow loading device adapters – including the DLLs they depend on – from a subdirectory of the top-level ImageJ directory (this is required if you want to have multi-platform packages, as Fiji likes to have); a careful analysis is required whether this is still necessary, possibly accompanied by an integration test: _Merge 'search-path' into HEAD_

### CODE REVIEW

**Comment by marktsuchida** [comment]
Thanks, I've applied the TIScam and zStageLabel patches upstream (SVN r14790, r14791).

Classloader fix: please see my comment on the commit (a204307). I'm thinking only 2 of the 3 hunks are needed, but if I'm wrong then many more than are in the patch are needed.

Device adapter loading: I'm pretty sure no change is needed (see the email thread you linked), but note that nothing in Micro-Manager alters `PATH` on Windows. Am I correct that this is set by the ImageJ2 launcher (so that it already includes the directory containing `MMCoreJ_wrap.dll` (and the device adapters and their dependencies))?

**Comment by dscho** [comment]
> Device adapter loading: I'm pretty sure no change is needed (see the email thread you linked), but note that nothing in Micro-Manager alters PATH on Windows. Am I correct that this is set by the ImageJ2 launcher (so that it already includes the directory containing MMCoreJ_wrap.dll (and the device adapters and their dependencies))?

You are correct: in https://github.com/imagej/imagej-launcher/blob/35a18fa14896d6dee0ef3d3e31ec0ded1e7b97d0/src/main/c/ImageJ.c#L1601, `mm/<platform>/` is added to the `java_library_path`, and in https://github.com/imagej/imagej-launcher/blob/35a18fa14896d6dee0ef3d3e31ec0ded1e7b97d0/src/main/c/ImageJ.c#L1610-L1617 we set `PATH` on Windows accordingly.

**Comment by dscho** [comment]
Unfortunately, I have to be realistic and admit that I won't have time to finish this... Too bad that the student who was originally tasked with this job left the majority unsubmitted! Hopefully somebody will find this ticket and use it as an opportunity to do good.

**Comment by marktsuchida** [comment]
Nonetheless, the Ivy, class loader, and commons-math3 items are in the direction that µManager mainline is heading, so this thread will not be wasted. Sorry we haven't been able to drive this as fast as we'd like to have.

**Pull request closed without merging**
